POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRheWxpZ2h0IiwiaWQiOiI2MWI3YWZjNGExNTMzYjBlODBlZmMxMjgiLCJpYXQiOjE2Mzk0MjgwNjF9.ZPUGcaoo_6uN_kl53gxzl1Q3RNUqS4yPQ1pjdfqSLaQ

  {
    "title": "How to turn on the lights",
    "author": "Day Light",
    "url": "https://www.daylight.com/",
    "likes": 2
  }