POST http://localhost:3001/api/blogs
Content-Type: application/json

  {
    "title": "How to be kind to people with disabilities",
    "author": "Sam Johnsons",
    "url": "https://www.miss-thrifty.co.uk/how-to-make-a-reverse-advent-calendar/",
    "likes": 10
  }